### PR TITLE
Modified whoosh sound.

### PR DESCRIPTION
**Pull request by ghost**
Here's one to modify the sound, if you like.

### CODE REVIEW

**Comment by sofar** [comment]
No, I can't accept this without attribution/license, and some way to verify that you didn't copy this from a Disney DVD (source).

**Comment by ghost** [comment]
Well it's your sound, so you tell me.

Ps. I'm actually kind of flattered! :^)

**Comment by sofar** [comment]
What did you actually do to the sound?

**Comment by jastevenson303** [comment]
Filtered and delayed.

**Comment by ghost** [comment]
I filtered it and delayed it.  There's a bit of amplitude modulation (tremolo) going on in there, too, obtained using a low-frequency oscillator.

I hope that satisfies; I know you'd already asked this in IRC and we discussed it.

**Pull request merged**
